spring:
  datasource:
    #多数据源
    test1:
      url: jdbc:mysql://localhost:3306/springboot-mjxy
      username: admin
      password: liu5201314.
      driver-class-name: com.mysql.cj.jdbc.Driver
    test2:
      url: jdbc:mysql://localhost:3306/springboot-mjxy2
      username: admin
      password: liu5201314.
      driver-class-name: com.mysql.cj.jdbc.Driver